
ALTER TABLE game_rooms ADD COLUMN IF NOT EXISTS questions_data TEXT NOT NULL DEFAULT '[]';
ALTER TABLE game_rooms ADD COLUMN IF NOT EXISTS player1_answers TEXT NOT NULL DEFAULT '[]';
ALTER TABLE game_rooms ADD COLUMN IF NOT EXISTS player2_answers TEXT NOT NULL DEFAULT '[]';
